---
- name: Verify
  hosts: all
  tasks:
  - name: Windows | Puppet service should be functionnal
    win_shell: Get-Service "puppet"
    register: puppet_service_result

  - name: Windows | Puppet command should be functionnal
    win_shell: puppet --version
    register: puppet_command_result

  - name: Windows | Verify commands outputs
    assert:
      that:
        - puppet_service_result.rc == 0
        - puppet_command_result.rc == 0
      success_msg: "All tests passed"
