---
- name: Verify
  hosts: all
  tasks:
  - name: FreeBSD | Puppet service should be functionnal
    command: service puppet status
    register: puppet_service_result

  - name: FreeBSD | Puppet command should be functionnal
    command: puppet --version
    register: puppet_command_result

  - name: FreeBSD | Verify commands outputs
    assert:
      that:
        - puppet_service_result.rc == 0
        - puppet_command_result.rc == 0
      success_msg: "All tests passed"
