---
- name: Verify
  hosts: all
  tasks:
  - name: OpenBSD | Puppet service should be functionnal
    command: /etc/rc.d/puppet check
    register: puppet_service_result

  - name: OpenBSD | Puppet command should be functionnal
    command: puppet --version
    register: puppet_command_result

  - name: OpenBSD | Verify commands outputs
    assert:
      that:
        - puppet_service_result.rc == 0
        - puppet_command_result.rc == 0
      success_msg: "All tests passed"
